# Generated by Django 4.1.2 on 2022-10-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contitent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contitent_name', models.CharField(max_length=50)),
                ('contitent_slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_population', models.PositiveIntegerField()),
                ('country_description', models.TextField()),
                ('country_capital', models.CharField(max_length=100)),
                ('country_flag', models.ImageField(upload_to='photos/flags/%Y/%m/%d/')),
                ('country_photo', models.ImageField(upload_to='photos/borders/%Y/%m/%d/')),
                ('country_slug', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('country_continent', models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='country.contitent')),
            ],
        ),
    ]
