# Generated by Django 4.1.2 on 2022-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contitent',
            options={'ordering': ['contitent_name'], 'verbose_name': 'Континенты', 'verbose_name_plural': 'Континенты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name'], 'verbose_name': 'Страны', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterField(
            model_name='contitent',
            name='contitent_name',
            field=models.CharField(max_length=50, verbose_name='Континент'),
        ),
        migrations.AlterField(
            model_name='contitent',
            name='contitent_slug',
            field=models.CharField(max_length=50, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
