# Generated by Django 4.1.2 on 2022-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_country_country_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contitent',
            name='contitent_slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
